set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g status-style bg=#63d0df,fg=black
set -sg escape-time 10
set -g mouse on
set -g history-limit 50000

# Start windows and panes at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Reload config easily
bind r source-file ~/.config/tmux/tmux.conf \; display "tmux config reloaded!"

# More intuitive keys
unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Vim pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Keep current path
bind c new-window -c "#{pane_current_path}"
